name: flutter_clean_architecture
description: Flutter Clean Architecture Example
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1

  #DI
  get_it: ^7.2.0
  injectable: ^2.1.2

  #Network and parser
  dio: ^5.3.3
  retrofit: ^4.0.1
  equatable: ^2.0.3
  copy_with_extension: ^5.0.3
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0

  #Utils
  package_info_plus: ^3.0.2
  analyzer: ^5.13.0
  flutter_flavor: ^3.1.2
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
  retrofit_generator: ^7.0.1+1
  copy_with_extension_gen: ^5.0.3
  injectable_generator: ^2.1.6
  flutter_gen_runner:

flutter:
  uses-material-design: true
  generate: true
